### ISSUE TITLE
Error getting package:  pattern must be a valid regex

### ISSUE THREAD

**Issue by fils** [frictionlessdata/datapackage-go#15]
Using the code at:  https://github.com/fils/THROUGHPUTDataPackages/tree/master/dpex 

Which is just a simple app to read and open a firctionless data set to work with the raw read.  

At line 14 of file:
https://github.com/fils/THROUGHPUTDataPackages/blob/master/dpex/outfitter/outfitter.go

I get
```
fils@xps:~/src/go/src/oceanleadership.org/frictionless/THROUGHPUTDataPackages/pkgpress$ go run main.go
2018/03/18 10:00:04 About to listen on 9990. Go to http://127.0.0.1:9990/
2018/03/18 10:00:14 Error getting package: pattern must be a valid regex
```
I'm really perplexed here.  These seems to be an error come from outside the datapackage-go package but am not sure from where or why?

go version go1.10 linux/amd64
Ubuntu 16.04  x86_64 GNU/Linux

I feel like I missing something simple...  but I can't see it.

**Comment by danielfireman** [comment]
Hi @fils , good afternoon.

Taking a look at the [dpex/data/data/carpLakeCoreStratigraphy.csv](https://github.com/fils/THROUGHPUTDataPackages/blob/master/dpex/data/data/carpLakeCoreStratigraphy.csv), I noticed that `Depth below lake surface` column is not composed by numbers (looks like data bellow line 22 should be another column), which will cause an error. 

Another source of problems could be the use of the type `text` for `Notes` and `Core Segments to Examine`. Text is not a valid type as per [tableschema specification](https://frictionlessdata.io/specs/table-schema/). Please use `string`

Finally, the tableschema project was not tested against Go 1.10, which I've already done.

I totally agree that the error message is quite bad. Could you please try those suggested changes? We could change this issue to have more descriptive error messages if your tests pass after the fixes in the data schema.

**Comment by fils** [comment]
@danielfireman  ugh..  how embarrassing.    I sorta forgot I'd never bothered to make these in to proper packages.   I'll try and fix these in the morning and test.   

However, I did pull down the simple-geojson package from the example packages repository and tested with it.   I still seem to get the same error.   I'll test things more in the morning and try and update this issue with some proper examples and links.

**Comment by fils** [comment]
@danielfireman 
So I modified the code and put in 

```go
pkg, err := datapackage.Load("https://raw.githubusercontent.com/frictionlessdata/example-data-packages/master/simple-geojson/datapackage.json")
	if err != nil {
		log.Printf("Error getting package: %v\n", err)
		return "Error getting package"
	}

```

in https://github.com/fils/THROUGHPUTDataPackages/blob/master/dpex/outfitter/outfitter.go at line 15

I get the same results
```
2018/03/19 09:07:56 About to listen on 9990. Go to http://127.0.0.1:9990/
2018/03/19 09:08:03 Error getting package: pattern must be a valid regex
```

any guidance on what I am doing wrong here?

**Comment by fils** [comment]
I tried a stand alone test..   to ensure I wasn't messing up other elements...  I still get the error

```
fils@xps:~/src/go/src/opencoredata.org/ocdGarden/frictionlessdata/rawread$ go run main.go
Raw Read Test
Load error
pattern must be a valid regex
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x714c26]

goroutine 1 [running]:
github.com/frictionlessdata/datapackage-go/datapackage.(*Package).GetResource(0x0, 0x7e3f03, 0x7, 0x1e)
        /home/fils/src/go/src/github.com/frictionlessdata/datapackage-go/datapackage/package.go:47 +0x26
main.main()
        /home/fils/src/go/src/opencoredata.org/ocdGarden/frictionlessdata/rawread/main.go:20 +0xde
exit status 2
```

with the self contained code....  

```Go
package main

import (
        "fmt"
        "github.com/frictionlessdata/datapackage-go/datapackage"
        "io/ioutil"
)

func main() {

        fmt.Println("Raw Read Test")

        //pkg, err := datapackage.Load("data/datapackage.json")
        pkg, err := datapackage.Load("https://raw.githubusercontent.com/frictionlessdata/example-data-packages/master/simple-geojson/datapackage.json")
        if err != nil {
                fmt.Println("Load error")
                fmt.Println(err)
        }

        so := pkg.GetResource("example")
        rc, err := so.RawRead()
        if err != nil {
                fmt.Println("rawread error")
                fmt.Println(err)
        }

        defer rc.Close()
        contents, err := ioutil.ReadAll(rc)
        if err != nil {
                fmt.Println("ioutil error")
                fmt.Println(err)
        }

        fmt.Println(contents)

}



```

**Comment by danielfireman** [comment]
Hi Doug, sorry for the delay to answer. After a ton of debugging (including change the library we use to parse JSON schemas), I believe the problem is twofold:

* https://frictionlessdata.io/schemas/data-resource.json (the canonical source of schemas) has been updated and this change included an invalid pattern (that explains your error message)
* our schema registry mechanism had a bug wasn't picking up the local cache instead of the remote one (that was fixed).

Could you please update your datapackage-go and let me know how it goes?

**Comment by fils** [comment]
@danielfireman  I just check out both my codes using rawread and they are working as expected!

Thank you SO much!

From my POV the issue can be closed!

Take care!
