### ISSUE TITLE
Releasing version 1

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-go#22]
# Overview

Hi @danielfireman, I have already shared with you the new status page:

- https://github.com/frictionlessdata/software/blob/master/STATUS.md

Recently I have release version 1 for a lot of Python and JavaScript libraries as a finalization of this iteration of work. It would be great to reach version 1 for other implementations including `Go`. 

Because the initial stage of development is over I think it makes sense to release version 1 no matter what is missing at the moment. It will just communicate to users that currently the package is in the stable state.

**Comment by danielfireman** [comment]
It is a great suggestion. On it.

**Comment by danielfireman** [comment]
Done. Release [version 1.0](https://github.com/frictionlessdata/datapackage-go/releases/tag/1.0)

**Comment by roll** [comment]
Thanks!
