### ISSUE TITLE
package RemoveResource does not work

### ISSUE THREAD

**Issue by cschloer** [frictionlessdata/datapackage-go#24]
# Overview

Line 109 in package.go (https://github.com/frictionlessdata/datapackage-go/blob/master/datapackage/package.go#L109)

reads:
```
newSlice := append(rSlice[:index], rSlice[:index+1]...)
```

it should be
```
newSlice := append(rSlice[:index], rSlice[index+1:]...)
```
(second rSlice should be `index+1:` not `:index+1`

Currently RemoveResource actually removes every resource except for the desired resource.

---

Please preserve this line to notify @danielfireman (lead of this repository)

**Comment by cschloer** [comment]
@roll Can we add this to the project board?

**Comment by roll** [comment]
@cschloer 
done

**Comment by danielfireman** [comment]
Released version [1.0.1](https://github.com/frictionlessdata/datapackage-go/releases/tag/1.0.1) with this fix. Thanks, @cschloer for reporting!

**Comment by roll** [comment]
Thanks @danielfireman !

**Comment by cschloer** [comment]
thank you!
